import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import Providers from "@/components/layouts/Providers";

export const metadata: Metadata = {
  title: "Dana Masa Depan",
  description: "Generated by create next app",
};

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${poppins.className} antialiased`}>
        <Providers>
          <NextUIProvider>{children}</NextUIProvider>
        </Providers>
      </body>
    </html>
  );
}
